apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ed7MlUfD24dn86cmyyPcHxZqowgcPt2+HyeNWeVY4Z2E1Yy3lLwFHz34M+HDgO63L6vXoLN8o7YT2nuEUN21FEWqWS0jCVMyPxHWAVRcC6B2jpj53guu5/DWk64WqWtZtColiUf7IC0zK/eIj7Vge5p4TbR8pvEJvebS1aHTJd+6FZqetSnOGBUJZORKDBMw5g4Od5i+qTeesRwQH9URrxhnNg/6k1Vfb3wILdzmOPh5lu0XH+AksXPdqrsfB/z8RQYzrch5fG/7RuKmo4YKlQvJY/5wfX/9Qp1n3G+Bi/z0R4rzB8TWBcxM5f0hL0eUJNJS7uyAeWttf0LGS7g2wtPF0Onsm2gJa0m+UvebzFZ9A2PXibQ3k9Mpl628t+gL,iv:U0LMNBhrmlt30Psal8NLoiM/2IpSMxsqfFv/F2d3ROQ=,tag:z3rEEkeWOx4uTDWsAQYv3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:PhEpe47nt8BzG08f+SwhyHox3oZ1JuairYILmBCLdGtZkqwKs59AnTUwzNzqUkOPDnw79O/8bygeec5SGSsRbEmmPQDPmVdHL2w0W3m5E94oXd6/I7bB2Q0hYLFrI486G0oYMyzlrT6lxjfmo+cHKCMZ6+AIZIP4MnGoYOM4Vrgy/c56AebhZX8kRQuPwL0Iy/TEqvZsJCfdW65x86OL4ykI00num1xxKDfPFIBMoZfyDdT3tBTMLuqECwm4l9Lcud53cgNzeqRiafXDRA==,iv:BbJrt6N79TPePFK5cIcQFoSv7b6SJxIxZqntDbL6rV4=,tag:H4zN10XGSb5uKKAzzrwFRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RWnZoJzzkOIZLt81sfzXjboA/mxADPNBQzm8fNKvCQt9MKCz0DZBR+dHEMaCXY6bcrAWsQ+CT/OevNB8Ect3Hgraa5CO9sERyiJsthbfp99UShHS1RMLm0TtyIfeylmYC5v4U2qn4NLot1xg5rRD30jU2UresNVyq8boVXp1xXtA5WN9qmOKfm92WV7aYY4gNMvZqoUsXXWpRLZOr1Us0O3/IHLpt6RAGFyB,iv:bhCGf6CZlO816V2trLHtLDLEW0Zo2CE0aRToWY/uytk=,tag:OXnizdUr30kw5MnE46kk1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QmFaVWJhNFp0MW0yUnRO
            VU9vYkNMSGJNQkpkcXZmODhYckVaaGt0Nm5ZCjVWQTZxSE1JMWlpaFFDYzg3NFNO
            ZFEwV2E3cEtsQjhsdmxhWTFFeS9UZTgKLS0tIFpaZEMvdmFzdWZjWkYzb2pkMVJm
            dnRxWC9aUTRsQ21IeENWbnNPRithc2MKtMMhAJj61k1tAmqcIy9EvbI9k1kHJDV/
            oFBXgK6daTcCPFU5/SpA9rNneoDq8aLSxK8wuGEw8Q3Y06PO8ix07Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T23:18:45Z"
    mac: ENC[AES256_GCM,data:OLOtPrflKijUcVfuZubsj0bKzAYavNJLYW1zf+OnYLj0CnzsLGxJsVIcp29xLeuL+TvyOYgSrhtPfQVDlsciwm3m5arSkshGkWOzpIjwsIaljiwtizknFW2qB2nSI+8CEPU6SjhjKehk2qb9J9CyoEuLm26XAZIkZJDwbnR7lKU=,iv:Y5jVpcd3xL/OJLCVQpmbXDind8r7MyXPEGaRbNzcSJw=,tag:scDIxr0PlUBXYK4ErEEY/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
