apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mlQZ3UwM3Vvxidq+ZmX1+GlnEG/1EP0B185HPLgbG2bt+ISSosRhpUsPDg/AJy6vhZ/lJqoEHVB9ZK6aE7VFmlvRrqVMGMYvyQ5amFItoPV17K6DYs7gQjj7lv3Zkz2/POJYt7WHkidWyKYjBOQBycIJcpNG7GAjWhQbqMmBR40iOcy7vj3tSW2KW9tmCKUXMZDhE4i5/l5MdH+aE+WYkwm3yehQ4TT6RR6ZiA72tXFJagRbtN4g3OXjsLK8aybg5HJbZktGfqVG/R+BPAowNj0rK19Cgfea29+DgTrigwcIKsnzJUNxTKBz8+2aX+w1jUbJFtuIsixVK9k6j0w/xweQzmEyqp+TwylHk62z3r3rLVpfm4Pk8RuPgD0LXmAx,iv:Z6pQJhiOgo0Dcci/agvJ/XtdZK3Q+QL4El0Xd5moKKw=,tag:qRebK+tbDOirK3gqSAtZgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LED9OV3/s+znRUz2UbrrvARuFCI3oSoqY3hJGqPsO6ssIsGT5Npb2TCYZ8DmQ5EoMVI5gctB7dW8Vk7vhDZSUT/Wx0cop54wdtgoBnU+ThNBelBEe5zCj0UKgNNg76ohxzcbzKpsYv1pSgeLuWl5/dDQXFA48VDVRK4Ozbs5zUcGd7VPXu+GSK1ILqn7SLLgRitSwEnFc8XaTcUxdVAlQ7hSixXpZr+yE6UkPNgUK0jbfdEegWPU/AZk3N9LQmZB7Y0Rpny/KYzZYm19fw==,iv:QUGbiv2xEf3hWeBfjf3gklZbISRjlHaUXZbnk4+LzyQ=,tag:nHzjEpdL+AlKWipvlvl+vw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pt/iFUJKZ73S1thkY+4JWz/ITrJLgP3wHVce3jjYq6W2SCcv59DbCG0QZtOeZBpJdDrsdQM4rl0rYiLkhLU8fWU8dEtAOD2zK4I7/Ub9LUCxxCN68KjYD+11zUin87qHBdFFLtPJKlaJbS4tcPHWvCXc7IUT1+gWMYWwJjJwpHI2hnN3WILgv4Ku7FIQWkEtpAw27JPp5Crd+8f3nY7r/+MjBL/tmeQESBq0,iv:cC9+eBPWdgRniAaCm2aW1o7b84M4rZhy4eV0/3MLQww=,tag:b5pMfrU9Q+/APkjpBVNhyQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ODg3N1RUMDdiT3ZTc205
            aUI5cXoxWE9sN3puc04ySkgyR24wcGhlL1VVClVib1BUTVJiTzJPWFdKckxqY0RC
            Wld4d2d6bnR0SlkwV1dpa2RnRzBxWUEKLS0tIHFYd0xTaERnQ0JQVG5Sd1pnTUtR
            eXlLZWgzUVNDMWJyMjcrTzJKY2ViZ1EKGMXTeozaPaQl5GNfIl2foVfRmcFyuqmR
            X4YW4R4FyJ5n4e4DqZ1+teQOHOrQh7cTq3yoXuzXZbXEBea2rqFfvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:39:27Z"
    mac: ENC[AES256_GCM,data:EvmlapHSoWvo85Shv69nUfMpFOpeNibfOrb9xMSlpGMjylZ4I+NtNUzZNESyL4evXWvOFHOo8KNwfmHADxJqDNop7J4kiHFHlCFErKZSVL8CD+0v54ZJ5+jTvSjOEx0lECAHEuLu5Vc1QB5eN/VOJj0Ustz6apteITde5MJyTvY=,iv:C9uY5H2xUE3F464Qyr3KUEgZ3UL8Cl4oGhTC2D0wC7g=,tag:qksuaLN1+8v0kdDTMKj7aA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
