apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/VXQvdO0UT1xm2NNdypfNlHI+l9bGQgoZiO3iMHaoYjwaQmecxDSGPsE0+U+78xU3TrqLHQEAgAyZ85dimOtlkU+/UKOMDhrqU+J4xSFIRv0fGHg4/Pij6W6F8QLE8lOXB/DCr04rIOrEN0Zk+JxDEYEPV/X8TwuRBc58nuVs3Kwn0okR++K4vMl9eFqmhbNc1G/XsTj1Nm69O/kWcS3+ns/Xsu+prTRHid133nSNiLsGz0XDgV7XFd+jwJl8Wzd32JCcmousBlGLCSYIdkEUpcDdH94fO1kHg3QDfXKJwypt5mWSf8S+35L/R7rP8eo0vkiNEaWMao05X+SdvkMa5Ed85cXNHbbGB9/tqQiWrKuV21uf2HPho3rDGPFwnNL,iv:pusbcJ0o2W2SXvlsVz2s1dYJ5co4SMkBYIjZxElVsO8=,tag:2QLUJHTYkmXr8RfsBT0Meg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZpOTUKpedpnbNoCtPomEU745xuJFZ6ZQcJvYtqI90Z8al+ro4J4Nog/nAjoSqLHYaeHMP1Nok5JGPEAXidZK3+SAy0Ity+48PD+MhyBtjclNysKLvnTW5YWuffRPNaRgB6jqgOaGNX5EeTSImvpYBMyc9s/PXQ1oEAQBQU9aUY+k8sT6QCN+6+OVgZpRLd6d+PrU0tFZBFhxcvKaGnqYU2G7D6z9hvZCXbsrTqzWC67PIsJE+RWU+jfMAnByHzS4r+UFg7fqkeUlogGuwg==,iv:A80rarLnj6LKXwUwN2mXpoPMGukpRJuha338LhXI2J8=,tag:62s+PSZ7bF1uWd4rDHcoQg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kqB2RE2dt/uMPYMKMbgTHAJDnFmUED7t3jHASsgvJcgzyDd5yjeDfyvwb9COH5mjFsrZnQxxXNSFQmA42Ht+YI8gxL+jJgl9kPeezEtayVPESQH8DepS7JamiDoZtcm5R1PuTjKE7SCdxmTqhOI0DqX7p6+hLw+IynD4CNRNXCgY4a1eZjVoIOA7AljxJWj6Sk9HHxOPWeUF96T4HbgikwqyyZoMS/7/6rbX,iv:9Stac1Md9eD10grJLCi2JBudHzrKg5GhlCbrwrv0oqY=,tag:tM6gUKOCImCJTx3ddNvMhQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcDc0ZVdrbmFiOXk3TkJr
            ZnBlUnNLdkdsU2k3OU1uRlAvaHZsdStRYUg0CjBFNlpzNTA2eTB1M0xmSEpuYU45
            YzZ6d1Vac01IZ3ZKOFYyb3B2blZOK2cKLS0tIGwvUmhUQ3JNUCtZUnlBcThKcmhQ
            cXRJTnVZZGVrL21NcjloSTVTWm1hL0UKCG15zLeB1C4jw1zcyE24EOH864g+VCzV
            nnwNTgmSyadCBfywJGGqsHniCE5V5lxHsZbV9JUlSE2/vhEpmykcaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:38:02Z"
    mac: ENC[AES256_GCM,data:5bFs8uuVMvSigeFp1NGq9Bi/HldZJnNbEiLw21tZ0OIigKBD3VIhhwxNxGor3yAOcHHsADbmqCI5hk3hoVXJAirYuRHg8QJl8/HnXAvp0VbFsngUPLlB6BBCD1aEZ/m47cOZrBBUYo5FhJhBgbgi0v0viCyxy3sCEbQ6WeprhU4=,iv:jeT+6NiPVlPCvwn8bXXXW0+DeLtPYlKrEddpvfMwgU0=,tag:UlXrs7hfOQVMFHrBFrAQgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
