apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K0Ty1YeIekmXFj8ApextehhQ6C1R/cbv/bUgp8oHUx8/bHQQUiqoNcB4I1Dsed6vSSAxVcaexPv7tAZl6+n/W2b0kMqUOdm4tKTClT1JV4zDc4OHbyC60639fGHzdISrZ5YMiil92Z3MXbA8jVQ0xUDmAyPiTVoi/goKsyV5sxYXbZbqurAo0UQyXAGGZntqIimfUEe03vNdA3pZrEZkkVvLzEIbHGYy4dHhOB6S0ZrI3RJ12FHpGRw4xZ0AK+rWlNm6e+Mqq9XgEH404qxLCOB7LQlt1SYgDNJGaZpp461VG9vKg9kq8F/Mv4Sre9cB8L9/yuoUn441uvWvbpS1V5rMlIDwIFChEd4w2FGP3rUaQ5cbA8bkcdJIXbGu/X0s,iv:HE8QRNRY1pzbUzuVVRKR+8SKd/xFbCpfnu13OPf6k9Q=,tag:5Q0EbExY536q2uWC9TYE6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:5wm6JleqE+EOlrg6GxUC/0ionKqnmWIA+HhVNrZvrDQyuWd83cdyFx4lFPJtw9g6SOwGtP5/fclfRIyLR+Vy2ntvkUNI7VFrqJgtqFR8iKEwB9cMkLT/QncpyLzLMQfW/mu4OhCn+i7Iw9fKBpSK2Q2aX6H/BlABwmPa2StOVfBe9VTXsPBT9ZqtLre2Va1CBj3bOrPzRhm7Mh2GRC8TU8G/naXLuMrt8o0ar/zUbOwXdvFYEOuTn5X+VDorXuvc0oSSHMYpCLg3setymg==,iv:hu3xcGfXz4KkyeKyqGImYlVYLC8htRehJDKydWujgs8=,tag:ZFhlOTWSpRTEk+xJESVF/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:iQO8cEBdwdsTYlWjKQXFqMynk0Vpg12ASYK9+/R3qqJ0YECWTE/tW9VeBmOFe5g06o1AaGMA764nkizxENk2268WmeqY87mNem0x/QTouzwfhzntasU7KYUb3w+n5SZ42gBaHCskjgV1j4wjSj5i4wf/o7gW1e9ZiunEO+FX5zBdBre+zfsoEsbilTTQO7HgDKCMr6iBLX97LqTPfwLmzIF9N7zeaugg3uz+,iv:WIFNKN1hC5fOivRkHmCme04e7EOX6b+maU0qEBe8tH8=,tag:NAUbzmT+Z4r41W4rxZMo1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaXlseWFSQnhHVlNhcnUw
            Y2NQbjZNdHBXK09DYmpVeVdFaXpSQks2WFZRCllKNzFyMk51WG5sMHU2clhSVkdw
            eEhhbXlsM0JSaVkvMXdYNDdUNUNhdjAKLS0tIGlkcTdDR0p5VjF4L0pQeUREUGtv
            NWJGNDl5RkMwanBYYndxelNKU0M4N00KfQCEkYa8wI/OHodvmT1sYgwYLXjfyBTN
            4nuuvFERmAzIAUgh5GiSIrKwyaro1DKDG8F3rPyl2sJ6pFDA+AuOvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:56:54Z"
    mac: ENC[AES256_GCM,data:egMWeHX8SDZ5MPhYHA1vrKgta767+8TjgUX+0Ief+ArauALDPDoYxezW8wpZfvl5w5S+cpQpSeF+nq5fDYEHzrFC68eoH9X2TPQVgMneJfih7m/OyfK5FzyqnjiVj3KG3RGMh61wAtyoqXJQKD/kQGAqRAcPJg2siVktBKbBev8=,iv:ltJCnACv/cwOlKRkFHbFirPkPiw6hHfUH5P2BOG5gLw=,tag:wEYx+DE4v8HTa11QB0aLdg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
