apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vix2q7/7526w9uWdTa1ZZw83pLZF4R4mvywqMHPk8mqo8VzkPPTIjxi9TJsC3GufE5IIL7DDCfhZ4wQePZJh/D6HbwfBLzYrw+MRWamNTkWC9QcIC3Bu7F9tNSRxinoi6ctX3X2FwcSc39HZ8Wi855EvEsrpF7F/UewuHuNTY8qVmzX4sfDr/uoBoL71IM066ptt22AgmHiKU1G6uLUy72eCUneDZ9otwBPj45A2F7KkaEKVc9K7yTX7dveVNznmRCaPb+wvGnGDspn5qKRuh2l/I5pP+XNTint4XX3qigjlbTM8dlTr3lTAb7YimoLZQPy/ylJ6zHb9JWDzrA1np9U78nu9h6jEo0OwbgLMK/BwtFbKyI1ePuPuLtggCGD5,iv:ntJr1Cbp4H1zN3kyQjBGvNFK/CXRPsNxICRjyO+nB8c=,tag:XvSwK2RkulgjIGUndW/fCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:A7w9nIacet+bPuLJWT3GpLOgJVApN/NntfZ0g5hTGUmBCGE6Sq16KP1rIhloq2GBEWqDLrb2pu7fs8pEGqqKCV6w4s839X2fdBjhKlJ+t8lqYmvyM11ERArHbWbvu/1JmJ7nuPui/AOGL7Jv/WoMFEEhkmYHTNbWeP2n3SvoJ0HBjyHzXZLJ3JuE7N+inCycaGVS/mpAHbbMMTtq1OnZw6H00rbrNR+2kJmSM5k/VqWylb6VVCV5qTur5tUzr4kd2rvzOs1U3+RKf+plJA==,iv:EP1AtYC5m3tHd4ubGY7ifKjYDvYbm1TpOqV+IN4ZEMQ=,tag:Vo+VcBJJX7E9UTfpiJGAtA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7sG2c6TFnnU+uoyE60Nyp0pQsM0ZJanuh6POII2J1Mr61ukwvVj2meQRbH+MUsidfqIDev12Op0uzW9ZNqmiTdhkbmRv3LbJSGavOpo5VHilgX4JJXLIqB1xLzvfsrmtnXxcxQ63h8KUFDmc2BkA/3ETkL4MI6HYlanYOFDEHXJ0seoOVfFXlVooLX0l/IC6Vff3tKXXHE2pZu0WI+PdWQTG91FG5hkjDRRF,iv:bv9S1W2pG7W3aCb99ajVks13VIg2jQHgBLCeiBbsmp0=,tag:DT8sXbmBawCJAODfUbb+9g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ2RZcVJpbmwrdkdUY0hw
            ck96bElPbWVnRGtUTmNNSjI2eGFZVzdIeERJClk0OWtTTWlWRDEvejAyYzU3TFdL
            aWpnb2ZwTTk1Rmh6MW93NnlWUU50c1UKLS0tIHVGdWl4WWE2b21CUmgvOW8vbVd6
            b21YMGlFRkNldGJ2c04vYndDTXgrQW8K0Da70gYyA8Oyhbps0mxgsEKrkUu2317F
            D1/8qnRraN9TlRc2qbo906caPxORSuOuXlJtt+DPMwy1lkUqnDtC+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:58:13Z"
    mac: ENC[AES256_GCM,data:uLTz4m5uJSrjkF51fkdvgP/XtNWAQY8z46OVOeGsgWHrrSNIAgnlq0IL30E1pMxp/M5gE2lZiksarfyUm82r+Fc3U22MhwQi6FeBNmcbLZ2NMGS9knGgHi3rYxhwQ72OeG3TT4zy929zuZMcWgj1Gpdnnp/VBep8MfNMMcgk8og=,iv:bMm4srECn+MNGfg3QLukSVw8RLy9gJyQFheiitqWz/Y=,tag:Lxt4ojkPTl81eQThTzNXnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
