apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8uO87TxV4tEEeP/M1+1xY/PZJJie6iJfTEYzB0vx7ulk1fWovoDucxcOvjqHRYRHRtpsd87JL8r1kXuDCEOc47++C64cabH6fBt2ZRH4FiIPJrx/Io/0IfngZ50TetugP8SStR78pme05QSCBCBF4g/r2fcbXiX5DiYs07VsDgChvbxTjn7d0S1+5RZ5+wCw/M0GI2CrCJoCqWXVQdkvDel115h5JpYwVKE3kD1tRHtKIbj4+b5uk15Trr3aK1zpBomMELqx1H8abKIobGb1UGeGnjakfPn8QgU00Z4n/8LW82yt7GAF1W//Qa0VJPKRus+t7oGvZ7MP382RHkScnjMvAY7Y0bDpPNtm4HxEyOPhZCqgH5c0q3trcd1pQaiH,iv:m+qyGAw0Bd1QbKwYGEusjfx8NYvNL/+X4OXClSGyhng=,tag:DK0f7kv85rjDveZU6II/sw==,type:str]
    identity.pub: ENC[AES256_GCM,data:6hGpSw9p2WF0Wak49JuDnd1vow4LI267Kb6VyHP1sy5f7oZIJmyPEklNb57bFTtirjX2HNMA8c12lyCxffeo1y2WxsgtihEPqmi0b+4wTFqiN1X3a0+Hmo/cAbt0eIhHutH1AbqFpjr1nXZs6rOzqyYmBNhm/qpxdHbMHLi+FK/0Ltl3fWz509DvYRn8yHbxpGmJZbnBf3xhezwRj6jhMmRVOoeBKrFykBVCEzPcjsIjeDotFq8Kvti3azDYHOeFGUKyDK6/O2TmOWj89g==,iv:53Z42KIFxqXf990ueQYHbz2eoFycz4gTaoUUoXQ6PaY=,tag:PSV8Dxph1adi47hslSh7Zg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wOjC+rIeo++wZbrQDP3byuGJdo1yi6V5rr1KavXsb22bnaVW2f54XAsO11EpxA1x+xprdF6ceVEeCV1ZMUOxqO2NtjQhJoHL3+8qCMWK4KG5KQD8Nr1x849d2R4zQ8hXFRRKorqgUmsN9PWah2PlKM6EycPJjtNF0j1xGDVJu3D9EEiV/dORxwj8G+HT6w/MXOsDLCuZtgcUSwqkD3pg64mFlZ6OPqOLofoX,iv:LFEaWWghYfsDGbBRUx4+f1H5bsbPRQoDeKiYkSMZe24=,tag:Nb/1zhYjSRAoQMZ1Uqcr5A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZUxxQ1RUdklaelhPZGpT
            V21XZTVxYkJ2eG1yZlhsT0hDaDNXK2JHb2l3CmtsSlBIMHRSOEZXUEQxdWpOVWln
            aEFhenVwNnpKcGlPTkcvRnFPdkFJTk0KLS0tIDVYVlRDMm16YzlQUEdFNUtGUHYz
            bk5vNkFTV25VOTVrVWdFM1NNRTlIYUEKFTMJMpeBL9qEBhsAzV1UDk3iglRbrHCW
            604E/DgOWbzM+3ypN2S0XQJergbvttlGZoG48CTbtGGYYeFsVphTaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:17:26Z"
    mac: ENC[AES256_GCM,data:TFOZt8CBuzFvvUsNJ9wZlwW9QdZ0quq2en2CnUcOB2LacfWp3miHBrO4SzrPShWQddA9XBkgoqTF1GedWktlX4imSpumX2hqLK9Hka8qwZbJAz1QnU3J7MhG4rqcHDo7M57IDyITM2+WBUodSuwx4vQKdecq71DWViYXcZPFKbM=,iv:vV+OWbaDPl8+GglxiJODws/oGKj8aUla3SiO1+VSWlQ=,tag:NDW8GfFBbeqohBHsFmw/JA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
