apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eWsi3lFkCMzxzNeKkvdcFntt+Bz+1rz3FccbVweQ6PFt5jhNhzoHDBSI7kjpELz/RxSngqIcV/bwlZQQ+gTAfK/v2ZOhqg04HVc1OgoIB5SsSBBn3nrcEvKKuxUGs0p+HdlABiSpNIj5VegUnJUCSA7mDdWfo9dmx9GSFB3jAerTFl+pCd3K4CEYwkdCwX6KXMAfuy/MuraylLtZYXn7Zcibt0skXz9jzumhHZjxjWnaiExq3DxfiKh1/wMYx6k3Gtg1wXW0W112EduYz6HqlkmLwFSsbUYbhonhlV4uXS/dRNNh3TXv2tfJSpONmcYFowzhIQCTbA2JHlMuJc1GnDYOlMvhXAW6u+lGsqULgDwjSCiBOzuL9hkpqDtrj/a5,iv:KVqFOYxFVSprqlO/ZxAgUQ27zfTVdyYrr0ghWya4H9o=,tag:LWMoPJ/ECY3QtJ5KmzpAew==,type:str]
    identity.pub: ENC[AES256_GCM,data:ISPhani+h8RbBebnuneUzqesmfNp4EiH5wjbq4m/dLqtsKRSxPiqTwvrpFvTMi5WsMLvUhmb9/CRVCDO8Ip/JqGFg16dhJVjyFktpY8b7ccuVV8laU1bdyhrH/4By2nBuPVuqc5EsjA2TDz2Oxw2wFORIPl4MNn3cJHTvqylKBuh9m6bWqidWEpKU/vPcL6VEaOsEkeX6HA2G4rrFrnEnL3ntJoi76nCDhEHAtbN+Dde8a3XUr9mMKgE0ClcXC0F1OI6LLhYJPFmg7Jg/g==,iv:tcIwbfir85P0I4/ERrUInpjHdI7eTbCVjCqFIRen2xs=,tag:6ucqNTS4pvCqZNLtC3rBNw==,type:str]
    known_hosts: ENC[AES256_GCM,data:pq2ZFCI+msDhz+wH9leBcs3ls7+rBMU5RRLXfVLKtXWEA/RfZ1RBFhbPXPYItAz3NCy3tRBoK82ibpMNCHzResGJ/zztGMawnu6AM5wHTfKrN2CBFaUacqdP+Bg7vEHiphV57Ibxdzo48yCFTgLWvf+MizMCnXlsPr0glIoALLYKR1Bb0B9AmU7rRsC4HvM7NLdufNOPPmKwdql6Oo3vsgVPOt/+Ug+i0uV8,iv:yT0hq9eqyGVr7Lb45Nwd1AQN/qMb8kX2nICL28euNJI=,tag:3fELKl8m4ctJkWUwRrax0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbkcyRVlhb0xMSktjSmN4
            Vlcwd0FCdGlOM2xxa3c3NHBGbFFUQUdYdjFJCmFrS3B3T004SEZGUUdlanE5S25R
            ZWEvbEJaUGdxSExXMjgySnU0ZG80NG8KLS0tIHV4SzNscHZEMEQvR3cvTUM1RGJL
            NlhEMEhibG42L0lSK01MWGozVmJXMXMKUBQGxjrqHNI7QQaSOP+BYygRCET8gKlH
            /iWcA93znk9kTR4WhN31NvUq3Oagfu3B0pYI8O/TVLG+hb12bbLHbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:41:24Z"
    mac: ENC[AES256_GCM,data:z3E68KoP+kCTalDGVd83BDqQv7N+l4rrfEeIH0+oEH8iGnx/jd4/VUXvyAfTyPHRd7JawVvhRH+qo600bsrCCVJRn8DbtfAELWUPI8UW9qkY1vO7qt7vMQPiXoQf5Necmm2ilUcRXHSSV++PWKOENsawzR/rIGo7XlqyKLaTokY=,iv:JKi2kGDAyfxAbcqpkR7BXw16x4m5FSTDiW6Y9Dp3xp0=,tag:nPDkYvQsawuL+fnTJD9RLg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
