apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P47I8BbNPJKiOR1JMvDOAU5JrzYOzXNK8CSxj6zBc6z4eqp6spEH55e/8D3DM1m4wzwn945KuvE7M20TPEO+pXbpMwSCFaX5aAdDzK3F29y0jD6luxy5PdND961pbWE/FNImw3ZmJrobcqeQt9HsdUWMGcqgvLK4zsu6y3pwrx7l43FQWJIECrifqOdJ+Zyn56h9mhqNebOa9rDo1KERGPZ0I633yMJAnDBrs7UJgJtTCJ4U3BVwxrUeecxGKq59BJYYHTogIT/PRIyhaeI57eH41UgbntgQHd94RvGnexs4qOHe6657hejjj28ydIvULQEx/p5alkZD3s4tRMB8PaFmP4QTGCP1V3xgzZ1wtyeplZJla86WRiRXIYAvvDbg,iv:pmIQgx533skPUPYt0yvuZJBdqe9YZKS7OEnYriHhVH0=,tag:NRfH6RiXqJ83ndLWVVprNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hfH/CHVuMhN6jOElFj7MsZYeMyM1I9rkqez8Vp5oB3LZ/Mpy8ByCrZZyfFyCZqagYc/UY8xMlzVqsNVa7EcpjZJQVagyZlw41A6gKkJDLtoI9q85Ay2xMy5gVtf6OuZuiu2JQ5OPa3B58YgUT+hGgoUUwqr6tMgr1G56i556vzjAQZVgZjf4OJ6UU1gohzdTndoQjoYaasfjKaLgntYhBSV1gMZknmv3UA0KXzeupdjiKSzUFfBW9K2c2Vkf1Lzx994Jr+RDxr/z1LBT2A==,iv:aCeOBbnntTTTl5bDQ/XeVuFx+V6s2DgSpANnWsL/1bI=,tag:XYjI0bOauwNviSrSnOozCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:NlHKUq94SerYyJwvyf4MuZkcg2CGF4qDRvKd/4VDdKQaB0P6fJ5bnK51YEUeBG08wAOHYdjrtDI0y/QeFz/3qXgUTJcrIi1GhCC6xxI5RiZFkSk8tuNjdA8A0NDnOSDP0p0VOTQYZw6ENu2ZHlTn/qMQMXBC5Z+FhHOYGzRovcersipO3EVPNmS8t+DdEN6y4yTDll5ONsUdaIEvU0laNRoyCc2GA63yMt6k,iv:nPu2LEM/kz5zm6IwAkNs28VU6pIwYpnajPYla1mdgwo=,tag:Nsp6yspw/0b8x5StbhNvrg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRGhuSkJ5Y3c1NE9QeUMx
            K2VRU3Bad2Q5bUkzcHFRcVRCQ0V5aVphU0hFCjlsRnU5TEJPMCtlUDBGQ05HcXoy
            bjlmL2JhWTE4eFNDUVpzS3llb2UxeE0KLS0tIHJ6cjhiMVNWWGJKZUo2RnhHcGEx
            WVhyejU2dE83RkpTSWxlMTZOZHlQRWsKI8OQQlMtHFa1OGgDQMrGVoOWQjg66ebL
            KuDrv5oDw/M9FZ0HQuL1q+vBwLIYri0+SZULEelCt/8CLW4bLI//JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T19:41:59Z"
    mac: ENC[AES256_GCM,data:7y+Cj8hAY6hQXDh+z1cK4LMN+UkyKBr/qJLDYFk72e//xbHGXpRVRCg+mVBh6WUOezNarQPxrFR1PLjJlHm0feYoBv3M1yrnkVGQ+t340CMa9zXaCF98n9xmBM1mm84qjLZg17OkLLJSHNlj3q6bj/VL+Zr/st37QaS3RI4/k3g=,iv:8sX1RvWhcZ2QOh7900Pj69oh4e75DnyZgXrD+y7Rd6o=,tag:ebCXT0m8Z0Jj90OxEqtg3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
