apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:azzw5PZIi14YcRuGWP+rf18xEQ9/ecXxjF/QiyMdqzO1wppOWEGrBZPblShQIlCpo4dFfdWPUjIaQ/ZT08PLy0DOVb9LSokycdWKC41C3N8XsLDsK3mjLdt3DTEDL5ubRssU8ZY1AtR+d4f5hmQLdWmkFXUP9No+gxVdibhWKjEaqHe15eMXjpdRNxTPU2bTb+ifIZQF5jHE2iIpk6qTecGAFacB8AU6jFEod2nFrMQLNiyFfPh3CzV+hHR3rrvIXjgoJ4jLQ13HMCZkSkLfIsowvkc7Y7z/b/K0hYLLOtQLm01CrC1OgG/jKUlrre3bsGTm6S/GfLDfjbBZLgwRpxKeZjBtBwcVHIrLd4kiwZFqSpGEJEeIn3FjodAqwcuO,iv:A+7Tau1J7M7UFHU4d9Iscd6njCzgBWmLv9Ec677gG9k=,tag:AcJ8TtFcRlzQWb913+jXHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dU+BFfhFQb1QT9+iSV1s1nQdo6QAPiJeSAyC12jhyXE3st9u1liYNj51f04aDNJpAyuuLHAb1+whQ8+727K1Iy98yPnRXZUoocN26kjftdq3Aujiyw6SqdBSWG8eaT3caDx455kppMr8bB8yiUZAyvcFuScnlfDXifHUihuCtwBRz2TndXgJr1VoLE2yfKOBnH5O+4ixOL3eD4HbRrLz9hIfFcwix0segNbyb6anJ1SGP0lkXd5DwepRAUGCt8ZPy2qyx9VZA/bau3Kh/g==,iv:d3zYzmAMbzRoHafuyc8uYDX0Sq03WetYEhl5QoNaVoM=,tag:v56v/KiJJfUZBtawen0TJg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5p7hH0HIEYSo2Y4cys+QhhyOunO9Kt2uf1Nh+xlAalrK0RbgBTiImzJeXDmpeJJHhTqqKeq8ngZNhlIAZSdyta8UgffzHhv6ynpGiv48OB49hfFKugzBe/StveoR0Np7iSKT3W6q2P2o4KElbvcw2Lnd+F/ti5g4U9lcnqOU6s3B2skgw82k+7fd6CnbzIDzYekpVyeCxJ8V/vctmgSgkw+uHk8oDQCTw5kC,iv:Uh+TCNVpmalqDcl9DtOqfspd9jgD+AX5k6qL9qoEsdU=,tag:iDiJ9F24GhxVI/pPSEJmYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S1h1UXdVTDE3TjhjSzZ3
            d2liUDdaZFBtUzFLa0NsM2hQTU9yL0NyckM0CkZ2cVFpZnhoWDY5MWVUTC9NTk1T
            d3F2dHg4bjNXaHFFTmZLd3ZySkhDTHMKLS0tIEhWdHUrN2RwYkFpMlhpNEFVSmF1
            N3FPVTJGNktYTTVhamxSYkFxaFNQK3MKpD1j5CcAAqpfBAYrfhnct65eeSaf5wsr
            m9ajSW/dvM6ISgxMMOff2LbM9dkSJAdB/U+uwvOniQHHwd+WQ+S6XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T19:46:03Z"
    mac: ENC[AES256_GCM,data:BOFq1uz+ElRkzGjlSv6157JtzIr+1LQIXW2kdVqF9lcV41r+8+AvF6RLTxoz++3jyEn1lcoiR9MNtCKcQdW1/+9mpllijcF6jUQCWf0mQtm4y64dCaTIPSNlQprKBbrtRUn6h8IkYKn0cswKg9CEK2DvAKFn/FU56OmHPVJC3JM=,iv:1ReLkvg/JjX9gmzQqTdf7iqKBg4siFRPfMWUdfGexyY=,tag:uSuk0DV1gkZEjlD1l8NTaw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
