apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:23ExU0VN3++h3VlIQDMdnv4g164i19hkIlbj57ZwsSGcq//nmyEZXqxCC3Mf3ldRDVAy603EdM1yXdfE5txK9TdlcN34gnX2riDJH8lmR2MI4Q1DgM7qiyzPp4oB0gHWIQYZ6Ocx+uZC6iR9kLXUTX2hYIYTPaPJ+jF2pW3WZmjM/1ONot0/LBBh7b0FbmOusu1iUXRlRkQ1SHM+YHE8QeKqZ/vJZhZKIyKxu6P3Y2JqjYmFukQvNZe5c9Ja/Tqfdo34VBBPHsiRFMjNo8JzPDnPlyGtlWCxqfzXBQxHfgFAysnBZdKpD0yQbKWu/RbELEH6CL0xkUb0Nt7e7Cdt3bJQ+FOGrc5a6F03S9bIt6seBypiyx5jlEdJcBT+yboo,iv:Pyw61qdKf8IP6mVhW/kfxln32LZvb9f1q2aFRPgh7o4=,tag:JB2VL4JPlPuBmiF3S7kyWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:OKsSCsSnh7EOGGOW3jgkNBDy1OPpqVeXTb6hLbbUvcDjQI0fm5pv0THsOMgNGCSDef6y5aFoWuid0qlxlwC2D5x2rODo7vWgC2anWvUIUG4v42z9gnC3VJUcKMHuCNwZDpBfobkn0eAjinnjDQ/5uTBBnre28NXvIw5zQRFmbfTfh13ZDj2UD7+jVLE5B8lxENQ4+nz5CtSTe4dFlX+Iz9hj82MTl63gK9nRFuYTNDeW/Czai0GU9raK23B+DLb7KK5w38ERrrKHKL31nw==,iv:2nmEJ8C8e83yv3QSZ8jn+EtxayeeKAH2pj6UIiLr+cA=,tag:Hen7y5Fvlxdq/vfD0oDTSA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8E+mjH0URQ6j7+wZRmE/aXBs713JRsZ0h4BzHypkVq0tIByY4mWjwjqC8p687psoe5Y+EgWfRFNDa/7RA8HGtqk4L98u31OwikVjbCMGHX/nvJQpYvIY8hTTO7vHS10YtOzBDny/ssJX8yU8diwiBLQcvRacPVJ0G7nuUe3YBrq6b2fMTRl7dLew3WphtjbDO1UApPywgbUfQgjZdMOiU5UYQhh99r+HK66J,iv:WLr2ilZRFm3dpA4CY1VtKp6s3oxblc6KpXCWFzY2Syk=,tag:Mv2NYKJ/LNpvTFigJn8NMw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTE5YM2hxeXRwQ2pBOUhK
            ZmdpN3dmb2o0eGlneU05anY5YmIwb1orLzBrClRkM0hhdFNJNDVNRDZpUWhqbGpW
            MUsyTFJPVnZmZ2xVcWtpMHErUTVEeUkKLS0tIDNOZEVHMmhVY0lSa0RpeFNoUjY5
            M0dlNjlCSHRLVzhzOElqQWFBOUFFM2MKCD0GXgPgGkBpiYfd8dVXOJ1nvwOmKj/0
            hDNBmlYCHkSMqJ4zuaaWRS3k6EpaYXtQWTo0Z6u7FqfN/a/j4AhX8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T14:47:46Z"
    mac: ENC[AES256_GCM,data:2ByGq2G+XnU9Yf/4oZqLKlp8fiI6NKsS3QeVIwwh/9S/5JRLHQWyy0lXJbMwJ6faOJOnMo/oKXHnJkShwaBnvSzAFAADMEi1ai/A4wXfVrKJoSI8cBFUinHMh83/ESs1Zc41hnwIOfFEfJwse1iE7HbUvAoO4n+5ES3wGOio1XI=,iv:ZnQoeFcOSPoHH/F+V5JwvyAkWwGDeQRLyDu1wTIPvUA=,tag:IwNkEZSS7elYiYg6rXoY8Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
