apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6h2z+s0xaDvjHsdtAJCKtBbASEj/20tHGil/ONzlVeavacWCuzFXwoGOgYzkifTl+LV2yuXybpPvy1GV3MS8EjhJUEO7MWLeTxyK4y5oo0pTqgElidcq68ISP1kFk39Yqz0BgPcrkP2yXaC/p9Is+tD02kUtR2aSGvhgTwWqevjbLe4Ds/zrh4SzhrldNauPthGGr7bl2wWZUBl8LbogeU5PaPeAh2rsyjZ5FZ5uOiBxsMnNXldHuSOVewoZD6nj/RTOU9uHfZcuX0lL6ZRUfCSO3hLnPytE0dclfvq0SqCKM700zs7ujh/Ys7oVT+PilAav+Dzhd12rNpyXd2JWwGd9l/zLvFx5PQcQIE8Fg4HYucBcu8xlqk+tjaAHCDYr,iv:I34p2ImMmzqZB7M6WxeiRNXC0VwlhOfA4j4EnEuVdwM=,tag:LrNpIf8cudif1yK9QKGOuA==,type:str]
    identity.pub: ENC[AES256_GCM,data:K4LvL29R1ntflfftFcp8Y6CVmCH8E28dQuyLMe5bp/vG7AbFa3eJnnv2NH3kjnBHehNzhsdsC1AhD23NFQDW1hlli+1vMzMZw0wQrs+aGnhKmsii/N2owvqOcSQQtwYK9zFeODPU9xpFsdlRlTzKY77JgjmYpYtbXfJeU2BwHylB7lAcILiIyZKE/TKYbN8hWJ5E5NStFqW2uE/aG+EhO7Y0XQXkEE1eGY9z0Uvo+QN/tQtv24sd6ZwFV5TS60K4uiWGr9v7CPP6pv1pSQ==,iv:yUGCtoHHN/G4LwMyepcf0eHyaUpiQsPD4f17fhkYnZo=,tag:S7BAWtzF3LxcIKJrqSZD8g==,type:str]
    known_hosts: ENC[AES256_GCM,data:cJTtWmntutnnhVk6QPBXN2A4PYioDGoyNXQda0SBQnhtSABrm7hcs4KOXEXB9QaPM0ZKKupzac9+MWbglugwJ1z/85r9OIlOgM1IeEdNzrsHakJRp6eIMsEz7qJG/MtnWqHw3L/BX93xmyKQ7L8CKa+3y2ZQFsPikfRiRx/iSKIqcsOmCggfUK794Y5wePiP4e4/EC0epkuH8eB2isDbxAz/hVsFNmOAumJ3,iv:JGj+bBNolmEJp5Xd5mRWTTLU1FtOPRlaYAEM6Ck1wEg=,tag:6V9xhCQ5plGb991Pq0y/nw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQnBYS3NabDQzNEtpQTdi
            Z2Y3NkRNZzl1Q3VOUnpvb3IzQzRSS1c1WkFZCkxRMlZoNTcwb3VrMml4V2d1RnBm
            UTFNUXlKRU5pdFI5SnNUaDdJZUlCUWsKLS0tIEZOaUh0VmxyVWR3Q0ZFZnlQaU42
            NjFiek8rY1hSVUI2L2VqVTVYM3VFMUUKQOwCDLLkLjRkcNh2ze1e26tn4DvoyC1U
            ZHXiZIS0KryVlj4WhahWE06vq96nLjE4SzIwgj1rofNzOFDG32JC3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T23:15:49Z"
    mac: ENC[AES256_GCM,data:JUyIVq1Ixxg9u9AYOvx7q96XxmvbvCnCBPNW98k5M2LhIQy/G0CWPHiL0CEkJ4kRLprQ/7VWyZWBS/95nkAO38iuu6XcWkcr+Oq73xbfI+oAOiHFuH9ZO6UOCFEsbJSXjfEMUqV0gCiBAB5Y8AyNKiqmZxN5zqBDbKozyKYOymI=,iv:Wb5M8gNm+LK77DD6dWsWR3VWMk/SOb43fp0Dea1sqFw=,tag:1CsvNR9IMAFnFWwUup9Ozw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
