apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dFd0HtnvdJrwPpWZzWjSWvpofDYaDqOoCybxpMlgwEQTlez8qCPGp7I+CKCLePz2eYFUoy4EdEmPy9y3sHo5iaWMtx+rJKU/FuB1EassVANLKnTqgjoyc9zya0OXubIUgg548Bg2saTL758oNu3swSwAZZQmWtlEBZlbDfFv+WIJzFtM4CNsDBJ+pX7Zzl/etMbn0tnwNWkHz93LbrRfBxqXxE1TqcCJcbzsynrm+YAdgK5FqqtoQlMqRnEQDh2F/QTLRBDbaFAVYCvVrpm6CI9lcG2UfL4aStYaBjWjXBedDZlnHWqR8Vv0/O6QikiCUifseJ9yTYdblb/lPzaNS7IRgFGrfaQyd/7kCiFDYn1oupb7kdgdyDrOBuS6gfF0,iv:9PFJa+y29EeFvsLA3s9nsTnwEoyQuuW0LcGE6NqKMcg=,tag:SQdXwgcPe8h0PPuWjxYNDw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yOihL7byANWzkh+HE0YRG6vwe8pLz5Dg3+AfjW69Jre/L8uI47aCaiOHGKhlaA2Am91qLn5rLXp6tah6Zhj5Zog0TijwTExVw+P/gRL/FLepP34MO3wpg6A7MnFArJJb9wGXhzLSK5CkRNegDtfUwKwNk25/iE4G3srAJc5WBskUgWDsyIUieXPhVXeutzcXz5OIrZY4MuAjdaB11VR7sZAmUZdZl6IQTL73UX2J4h18AN66vKHsNjukuSXulhOKXjtPduLVWVR2SCJ/UA==,iv:OioaIB9JGesHUVCpjqyptD0/QTMjxh410APSJVZ2Mwo=,tag:ZHVr1BX5IownilI+r3AN0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:n/w0Z3JHxk57+zB0Rj91S8bhzlta2wDJBH9wlERy3uloX/CJSD05kPwjJ4AGwHgOqKSik8Y3/UB/klhUOjWGZWKnGI/vYnku76Gh7VJ/JlPCutaZ2+8R/FYeZ9TGGLkuR4LF6wJfhblzM0JvdTVZIVMlbQxniei9xC4/au9hLLv69C4DWHXbiMRQlCsJgxUH8whXm9mEN/AQmEXV0U39kJpP82B96slSzGCr,iv:RtKoMU2u/OKDQlDeiOFPhbU8nv725CdCOsE2ekl8UkE=,tag:tXcXwYJeUTEggmEjp4FJIQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOS92WUptZDVzTVJPS2x4
            dGFJYWRmWWJaTWtoN3A3WTdkTVdqdDNtbWpNCjlQeWp1Qit4RGVLLzR5eWFLUmRC
            SHdIYWVFRW5VbDJRbUEyT2FXWlBUV3MKLS0tIDBqNGdkbFhyL1NJK1VSb21MRVhi
            RTJ6V3l1Y2Y0dm1pMkM4L0xNd1YrWEkKlS5tuBJ9VIh7JgVerBtgsehlM0gZ3GD/
            PaUwgRuRnZnmBBNa/okyeItG+8jcbNBuyJHmG5nfI4i38E8Soal08g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T23:30:10Z"
    mac: ENC[AES256_GCM,data:wpdkAxvMt877aR4KUyDe7r1c9RYY4FapD5Rx2JMordvv9P5shQNkVmZn+N3N7ohNxsXMg6CEm2M3Kxnch9d4ozIUpWnS1SsL2WW50Ao54mQsXeT4DzqVDzYU79H7VuBODTPxuJL8REzNwGHwvlqcghODA+1UXfE7j1DRxud9hVo=,iv:VuaVuzcx/C0omDvBTcpzabjZPhjUotBf7XTKOA6Vm4c=,tag:bjTFEW9IoalVxYyjvwm1nA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
