apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4eT3Z95u3f7MVqATlLzz+79UDTj6rTJ0W2ZUHLW10tUaKPK5IoDqpyhNoWDwtTTFa/smoVaglXtNY/TgY+jSaxyW0Y/EQDujvGnq+N03sSBm2PrpHpII1crEsXVU259iMdEXcolVndi7Jil6C5DV3LpbxwSf31EKYKQC8upxFNli2iB2B+8DYru/RavPbgzddW/9Aof9La2E2b9jwTeeHOZuiovaOLFvrHJgs+LAMWVfhAQOR7XXNVmxuZzd/3aXZ8GU7ycdxRwccxe4vvxCNNrK1FRxTDkHba5UQ0bwzjku2vcogT7BLEZMM5+2cCcCIBv9FPiLt2WpG2P5cDqnQDKeARq89W6WNyJMK7chtSOXB1O1Gt0o34L+0avpLqbL,iv:M08pAi+didZHtIyBp/IKG1Vsqh5jITqAHp1MnPwvQ9Y=,tag:fwUgM/Z+L86b9bSBcihaBA==,type:str]
    identity.pub: ENC[AES256_GCM,data:gotv4yitbJ6jQ6HrhfSQUkfpbBF+FTwab3QGzOXgD2K3166mabIOD4YGHvZgQ3h4JfDoNUX6wfUnz6339MBP2m2D+F1x/eXXJa+spuoCbXpNgzDT1jnUGFFhm4pJFui6SKcCkd9tUsPaFG7w/rxnonkXzZLFbtusguCrZ06nXaINyNC9wTOGyDimIP8VHv7/1g3wqIHhuUH0Fali0sTtFCkPD2RPyLXV21vaJIl3iUDwgwlw/sI5TLHKsvUXyFAO6Xwi0Hg+BgzkzzARIg==,iv:QXt+TIPJRWNZ2ZsYjR6xByqZC3TZw/bXgF/oDL75JPY=,tag:WU/P9UnC2Szniqfl6LcTeA==,type:str]
    known_hosts: ENC[AES256_GCM,data:PJG53n7TwpOJNMGRbJlWQPlP8iH70cLLTO2mL7OJNUKAYSbp8jqFnWMPSONzWdRty/mq6qvpJWfBDxjYpffQHZoY7Y9pOW1GgYDVUfFfTDVHh7UqmOo108bmG65B+NrMvICQtMSaYfG/wazc50YfONKO6ooLvC2Dj5re71mi72TiyKDSYwuuz7Uhj7WIuf/BUHjpBSPJsB6s8lbcSvWt4WCRcururU0NAFcW,iv:mDKFa5iYsRreucH3J1L/h2mCVE1ulwMXGfeVfbFDZks=,tag:ZXPaoHUSVRYZ+LSs2pvyww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUndlSHRxbHhVMis2cEg2
            bk5lV3RMQnNNbUlZc25CWjM5OERPWHc0U1RJClRTbEwzckw0dUp0MzU2Z3Q0c21i
            SHNMa0RRcnZZK2pKQlZtYWhNSWRwOG8KLS0tIHhoWlJ3WU85dlpKeGhReHprSUNp
            eEs0dnI3Y3YwS1Y5ZjVqZkFpelQ0ZXcKXFm30Dn3ACgVQl01GmodzfJTxhSg42Tt
            Zdywki/mmCDQBJ2wnuFZQ28F1mM7Mp/9y4alNWH7ALNjAyWSK2SsUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:44:51Z"
    mac: ENC[AES256_GCM,data:6/NPiU/0PxBr1J5hBGUk5GCTUbCJKfQLau6K5UVjYJnixqCvkBX3H1hWK5BaKVhV1V3jxY7QCqM/w6PAvL007XxlO4zbEwx0/hKhYMbknWVcJzTPk5C7dv+npS9aTACwrYQPqH7XJXyWvT0HakV8algqGhCsR/YW51QQKKBZMRU=,iv:PMgymG8f5NxIyG/tVTxPkWrstiKrtbmvVRdhNxLxJUE=,tag:gTH0NGT9qp2w6budZy37aQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
