apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sbA9+SifnGOW52JKOr7EFpxwoRZLIzoHgpZpepyqZ3cF2R0CU62RZW7OD4snWxBXr+7X363y0mK/oZ8S6nkMW3dabrOUKdRwigikp0kHCh014/lPbkBF/3FuVDJ+MI7d1rGW3FHxmWn89rqvzUTwqoe/HcmEiN0dE2k8g07gj8zI7SQZ/bOo2mZwcfKppuPzLmCCDo/Xcle++lL7CFEM2i+Hdh4w8tNFEBvqWjUP/InnrTwAB9b/3jEPSkiCjsqgP81XLUtayQeZbUGoPF0B4zOIp5A+DQF2Ce56p7dPDT2PQRVYyLZRzb47lw/IE5QhzMl6Zq0Zm07HIb8ikbULJNIBtZfA07gvD/piLaALXmEsneuNTYDmG0vsHCDKL6nT,iv:9Cvi/l7RFzAhy4mDVunFcAy9J+l+IEpu3tPM3vUKhI0=,tag:/zAJFwExL9u9aDTwTw26hg==,type:str]
    identity.pub: ENC[AES256_GCM,data:5E/YDD8fDEtxxouVcB42LAeiUkq33GX7Q4wH0/epDVx2bgumbTQC5aQJ6O2cNlth1mxTDiUQXFihhuV9fMbcS7mAkY9LnqkEBm/dNRnx+Kk3BDpou6J6q9KU6wM78zfURMdIHdwZVlyAdtx5ZH8FWcaJtsUvRZE9L8BjtyY0NwP1JSQmZLCJYeeeAL/SVUlOt3Uo2MeVv1iJLYdGhF2xfQfMGF4jY8CFy7awzMTDw8e+58/amx6ueKa5HInTc6UgKyFFXdpbos01eKNfZQ==,iv:aahk8uAHjL261Hkq/voG2WceKYEwLC0FuzZ4y0VyOX0=,tag:6rKzKBN6EnJni/Twk5O0Hg==,type:str]
    known_hosts: ENC[AES256_GCM,data:KEGkmFnzjXFzLn06KJJaEkdm/Kd8iLzP6k2LIZElMi4oNtGqoh6GVALGO59URbC/YnN1leAAUFqoGuWBgPXP1bfWtBZOsLAZ8P1SbflsGmFSjGm0efKaKuK0viD1sg6d5I0CIwEOTV2lM1tiYotlpSglCV+9e683HD7mKsouuhvVXIfpeG5+vam88VNzU3SqKAZhCdwzQiJWdwFiGMBGkD1YHG+8dlu5+IUy,iv:0+5CuikY890ZJCWwBYfYB8DzQ9mKmcjSXKP/eJ/NL7k=,tag:eo/1ti6lRHuX5DhOx2oiBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYTFoV1VUTVI2VStaZ2ZJ
            Q1UrcWlvdWV4SXNGeWpWakhTMzNmRmJQcjN3Ck1HVFl4VXdyb1MvOCtzREFnZzR4
            bEZ2SllpaEc2cURRQjZzODViRCtXZzgKLS0tIEswMHk4K3VGMVZNd2M3T2VlQTFB
            RTMwNG9NZEJkeE1wSld6dEpDWThxc3cKmOd9xTmflaYB+NWq4RujF/VGfjtB6XAh
            bxJPd++0bTIZ2CHQJNfQhVXvW/vpJff8ZRLkP+qkqXThqrlGbm7cgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:43:50Z"
    mac: ENC[AES256_GCM,data:41vJNWs3AZpVe7nopbCSwZVWS5+CKiKtluFmP9F7xNqyBLEdKJ88RO1uH+E7xGHvxX19dp3HpTAA7ubLKekL/lBLVdAbZv1D/omMXSXulB2O+W+LmIuLgvyHEEiVDzgAY9IwFqNmzyvHY7p79c/KpjZjD6M6581UwuydjkZgoXQ=,iv:iVjjMY8d+B9ucfKBxPplxgoEDOz0l5FFpwR5LL6cxLQ=,tag:zY+oBgV2A7PoyG1beqn+uw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
