apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hsv1GSi3flXIq88RnpTycztJaKb7r+/lnjaDHs1iVNbGJuM+UPgSGMBGbOa4yEIOkwWQCoIyKX90aeENaY583UhTEUbztBas597Hf+9PK9dYDPnXhQIeHTXmPm0sKS9LBpyxEM7bom0c58wbMzC6/3NXfGRy1grS+OQDfu2tTVAv9eD60c8Ngwad/a+SnG0Z20Xtan7ztNoIDftR8EBFgHlmnXBsAodKJa5ITY2aebn7Bkl5tXXm5vIGO10H06W1/jHkobr7RlgdE6c0vz5mqG6HN91EbOOOIr8+nXN2odowoJqq48A3gQ5fTMV4fQCM4aFe//+dz+8DCDIBgGFNIO2b/Oi3Tk+SZZmvwEuON3mbhe3qSvVqO92LoEobqQsX,iv:893i0bhVVC3RXiQf1lX68MfL5OWFyAW6J9DQcPrCMdM=,tag:A7Ht7L0GpMuWsp0Og+mCKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:5RMyD1RPioHwnXKfHNgA0CyYOvg7JN6PJLUhdQG07FDD7O0IYT9X/kB75FGK/Gvje3ZB0gy/PkirE4N7ijHLn7o858z1sbUzI9rbfSgxF/C1Z1YpVZ20FDID9byYj27UpeV7/BXUy55cVSpDNaP841TUXF4+02UjftZHDRD21lw0s4aatunup8XpfkVq6Fxvmmz0069dieRRSb1MbR+LQ55fPcNbC+m0QpFRD8U5bJLjpkjqDMT602IkuRC17prMWrbn5ZejVtLqhqv6jA==,iv:7cpvCEyxXy55NmFX5VIWHD+pfcNfCRB8oJ8IGe8Iu6g=,tag:vQXo+FfS3TCNX+wpCPEV9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:0zbrU4PHC6gO7vFJtl9MKlj8oL8/ry41YxYE1YIwrFmHdkD+nauDR89dWV0J0GxVG8ztUWzPmlZjaKpJFkmZ8QDJstF5f6chR8XY/cLt/Fj5aJKCiuUSgm6sBgI113uNrhoFn7SGJUvFunjhLHiKxGcHUEIwk7fUQWP5b5azQJ36DB6/Mdi6/XlBmI3+ui/8KrE+NJrVsVvUjc9/WZwQg9D4DxBDW8xEbXwm,iv:+jgV4h+xYlorRWSYfpbggmTHi3I5Htvzlh9GhkDCokE=,tag:8A51d+ZI01iYSQWtjBo0yw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU0djb1RNN0VhYU9FMnhy
            OFZlczg1RmlHME11bUdCSVY0WEtGd0ZLWXhnCkoxT2pSRUQ0RitibWlrRDNkRGha
            cVhEUWlycXpmNmhOKyt4SnFlL1gxZDgKLS0tIG9YNFM5eE5sSytUNmxPVkhaOVJQ
            V28vTVF0UkF5ZDdOeG1UYjZld3BlaXMKaHBZqXziOprfoTa76N5Xxf5cu+eJCjd0
            WoTXG3r4B5Q1RZ/DM43nL0cb8iAE5goKtdyDeQbz1HOI19QU497+lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T13:34:26Z"
    mac: ENC[AES256_GCM,data:fLhJmNU3gif3toPMaSBRcMafMUimNRnZo5kUBmrDlUtbBvkCqW0sPRxYLtEgn7Z2PbMnzDSKL9nFb2+aWhgxVWS+aTa3nzNxoEGvSi/SPUvsExxkXGGrfVehIU0ClIAL/nV4y9NzWPX5ouocOcZxQDqJr+mgyMMUreTFkjfDhj4=,iv:ZhAT12aU89q96vqHLbdmGpTnS6ApLKQcyYeJLhGQYSE=,tag:JjGJFumMJsgN5MPuMO8qmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
