apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wB7i8zBCjeJDbte43GHqhqs5FSLqiOKi/EKiI2CQ+qfkZRzKvtOyz6W8D+Smt80jVK3ak3j2KC2qyh6BPiEYuwpegjKTsJPyzVTTziNc3bTZ6UVXgc5F94MyaWQJD+yJkCf4urr6qthRFVlGHkn4fjsJl73rD/EyxxKMYpg/bbJFU6VOWoZTmX/0dc7qLg8735Qm9epmOlAydEkLMmmwclYxvpVqGZyI0O1J5i/8nQNGWzOxFUH/pkVr0BB6r3gdqBo4ZV1XZB4XK5X3h6y353eijhu2uARpRfhqwirC7Kakgd6XhTtmLyWdP0/Bjkq05znJd8sZdmVqkMTaJin9DlV4BGmh1zgBf8Hr2LUIQLEiv4bDm+FSzzhnDUtBW0E5,iv:W2fpe5QOFVfFo0W38xost/D9Sf+sUq/4X/JTP+K9oiI=,tag:47+AoBq57WJ/QtZNGSLjvg==,type:str]
    identity.pub: ENC[AES256_GCM,data:djOfT5jNl58dAFi6ihWm7uVMDu0zFXp/WtJU86nPcmK+sY8n5u7TbyhHUsO4NFToMscXCZI/5cwDvqD2dBqTdYeWXuJu/WvXLF+OB572j+lboZxDvZksdhL21kQcAJBe6fkdLCzs7hGr9YVbBNla7PP4ZCSbPXFkQ/a/AIM5qDsrXnwZTSlPMRXke9HxRY0sK158lhYYOoXKx4S53vpvrg7Uv22R84wymFEzqHwhP5rtp4kVIDK3SOfiHsIYKsGhwrlUcXP5cyGbxEopcw==,iv:NBj9HLxZXwtdt+y9RnjsPCCUBZumBjLBB/uQhZH/cEg=,tag:awm2dLfl2L/wxHEXgMIJWA==,type:str]
    known_hosts: ENC[AES256_GCM,data:qBGJZXjKGGqeoMOz+3WPEHvdc4Plzwx9a3L1rs08+By5o8O0ka12wWG8W7T73Oj8l5u27xPGesZ1FBVQJCrdSdzcd9OrUAVdpSuUUA1xbZKN2aqZHqlKbMl0YMzYUtzaJzLMqTWhlhJSCs/I0y+08D2eAhh3I7J4ExPKmi4tUFOKps414MqlUDW55M2FWOjBlEZu7vJvhrgpcRzT8FUbOuuRxKGCnAtdkFNo,iv:EUnI4RkB+Y75yFsVIC5o+MOE58ksJE+yMwjG3f/FyqY=,tag:k7W4VLcz6v43W/IoNml0KA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaXYyL1BobjBpcDM4RmF6
            TElsR094YWRIeFRXV2NnK1Q4UGgzOWpza1hRCmdQRktRb3dvQ0F4dnJLV1M3V0Fh
            UTh3VkNKUC9FaThSRmZ4MVMxeWdJVzQKLS0tIFhPaWg4b2J4b1N6L25ZRU55eU5a
            VXh3V2lVaTl4S3ZtdUJiSHBBbFowOGcKSeUQ6bCQg/mwLoRurWwkp/x8drMnBABa
            fhh5BZc9+ksRCZ6kFB+eUwnM6X6Gc5hcdOgU9lxWQoYgpzh+uYcIbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T18:47:01Z"
    mac: ENC[AES256_GCM,data:4oOqcW2ebP5VWRZ+12Gnf4cg74DyRqUqD3QH7xFzs9Vr7fe/NJjOfDDzPseBd5gbPTaInSRtJPMO6T4WYWlCoV0vGqz4EfW1hO6O5V0RzUjdGwyHgDAKCJjoQo5Wx8XN3GkILAqLO7laAEPHAwlk3jMYkHCXZsmnQsGs2J3uOs4=,iv:6DlbwTKyafOokpws5ijTmzZxa1zeSgU1oWdXixDuzOE=,tag:LX/mCdv/XYFBIQQzMBxtzw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
