apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:h7oWz9BsBPU9smYaiNBTpKh50UK+/H15jxancw58EZoALAh1wY83E1EgQvWtkBZJgqwOHbmY4CqYHknEXm5F9azhgzYIsG3cxekXR1p2KpjWL/sVLLXQKRjS+C/bL7zlO4BxnoYoTwv5RqjWdsSqODhj7aXPH7PO8IR+ScNbU1I6HaaM6gDGKmHskHvaR1mfPStHB152sQbIDbEmMwjvPE2ynOc3mm/O+TJEG3Bn93tkdNHd2DyVnKerLn/2a8Fs8wKC9/vbBUbKyiD6o9P7ZHThswG72BQRqRgCM/9557mCwgkyhw+igyMdft/oQcYv8eItG1ntX6Tp360dSJ26PpmeE1GnRYJy9UdPVwu9kvyu43UORGkDlizJcpaR3yTF,iv:WMlB7mZw8qmGiaJxHTswrE52eh89uXvKNoypiXjcgYM=,tag:I+NNiHhvLWG7gS5zDlCaeg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jUs3b1HX6ar2Z6toL0JAu/eg40X0RcT1tYX/V6UgoHCV0aycwYg1X72TYrvy/fSujKj8BA/Y/ShpMQ9wlfqncKz3bXE3Q+1dxQlgUWNKhlaXmca02/lmmNBxIi/MyCvRSaoM3d0aRnThwZIODBtsFcHY1LYkffTRFeimLVDrpCjugH1kZ/2K+FFcGHxEbOY5UMtTY+8ywj6Hjka/8kRLPxweAWkTirucMUb5Y2v/nFr6yAhh7rsW03Es1NKd+sd1dKtMZv+MxIh97Umf5g==,iv:wy49yRm+IWkmR+R0238uVCKpffqHSQdOJcPH925F5TA=,tag:+pWtHV72KKDvXk5KUFAoOg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ftkye4ykMZ7b733tCxtX4EnHmnLxMVVZaaC1ZQw/lTYaZLgMcY3xodD718rVCH/968j6jriIVTLkYS9g1+SwkD2W5T/bxsxPOq1n8xL5eV6cn5YHOArDIhM+oTk6UOiKLTebJMNsnnYk/SEinZ3CccoAFcC0/ONIO90XZe9aJlkO7bJe71tyqgkaPMUbtKBIe5OtSp9y5RmjU9cgN+z2aLv4437uw2fyyncV,iv:mxTAspyhcvCxZkE4ZUf7I4mCV+Zz9d79b7pABRli0WA=,tag:YP4XKP0YAQ7TDNy86U2vQw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ1JPSU5yQ2ZGd2VnWUp0
            U3UxTjdIN1lkdlZiYnRQay84NVoyOHNSRzJZCjNGYytKUkVZWkIxV01NcG01Wkhz
            ZGVmU0NwSUNGbDZQcElpYlBvUXJWQjgKLS0tIHNZRFZaUHdZcW4xRnhCR3dTOWlq
            NFZrbU90Ym1nM08yb3FxNFBKU2xZSVkKuZDBq/PlDv5BCNKEnOLyy/nG/bC/ubbo
            hJVuCPzkMyIrHkPuhTlVMbDFEy9I941jk4WF1CVfFk+VG+lxyiS1Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:50:41Z"
    mac: ENC[AES256_GCM,data:XPfFRmZls1jfmPZeyftZjEn5Gb3RwYSxSM66K3wq3ekIp6qVeEtGrKX4IJ54ql4pYc0RwhrkeWHUqGpBQPCRyjrTRah38Qp0Bhh8ddfHZ7KMZNySh7eplXhkxetzZ4TIYKxibzcQfNcg/RkSuFgxrbwtPr9HQuHtagEi4u5XcZA=,iv:wVnzCVMvd187/3IYy/BY1Ycnossi53MkJifGZSfJCBE=,tag:EFEGqKbSnuOXn5Z6sJ8UxQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
