apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:f6FmFhbRUoc2OY1yBoXjtET6i5pLf6/tLphpwY8Wp2EZan60imneC5Ie67Fau3fShGMd7UioB7afLYMgN1XJSDF53FxoEH5u5EM6H0GMLngApFbLPfhl++uFaZYXX40EN4LHLcv7zOMT3UzAx8NuA4iLVyXidhez87YDi9p/IIY5YBQgkRNeOagm+adn82U9jSljGR7Leuq+dTKl8S+iZ91HsqcmTG09z0p4acKmqvbwHBJTVu34AIriwfKonouaImVcomWuhJH/fS37QqlOIvnBbCStpbLDypTdqpk8yxtkWv1Qqu8lRfc6uI4B2A53067NyR8bHPSB2/cA+D5QyjLWVCR29GjoAjL8b9LXS5h9XVtDB3LcVwN+9lrEAnGr,iv:8inMdgMa2CGsMg0SZLtAM7MTS3pTiDPk/zJHeZbf5Lg=,tag:PWolSVWIyNdl/tw+G6K3Ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:efxVvQyk/nvs6Fa3UJF+VhJXQWdl1O1nuvG5IRLR6lz52AqwiwmJ+VOG3WBgoGmCfxx/UnJw2yhKxhnQdGLHIRU/5JsZYdDFL08LzisEHEIVklpUQoT1BslMDA7Yi3/LgjXRADWZlVyr1UAH14MiNrOn6RqYhrAp6WHWZ3i1GrzfPfVhbeYkXYVN1tMgTAT0jHv5Graq+IOCMPl+KOWE4WmqAzoKCnQhjKEwRiCA9y7ituac3bLaslqs/XTROn/wws5QSosA8nhN2DTw2Q==,iv:OWSi9UfrnM9SfOnS58huNXtOxLg/qEhwyL2kXg374UA=,tag:to7g7AVRn3Z00Cvofj9gcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:PTZpcYPa+YPhD+jWfqiVqVAPJtyBg/v267CW6RbH77M9lPBMXCW7YYzD/gsw2pSLPb96xoGf818cxrcdWh2W+gmfp2a3heKYyQXqRi284v9xOpihJVLiWGsQzOZfGsJenadwctleicYs//VvHBOSokhendhjr+fYdyIoYOX5FR1CojLXAk8xCuPW4W3WgCqmPlZMYGPPqTECnFamckdKqf3MsVyFW1TZJAwW,iv:OafwHTa3YRq7mm1RZIrEjsjw7sQKZk00zAHbQCuDfd4=,tag:WXzWBLomiRM0HE3b+qtNmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uuf88z635k2mcmh8erg0asps5n3wlsmrjt53ahj7q93t6lgys4pqka35sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWm5zUlpDSWRTVFNtbVZ6
            ZnhHMVNBL1MzT0tBeVRkVHNRMjFHdlJCU2djCmNVY3hTV0JTOXZaNWdOa2VmOC9M
            NHA4L0hPYlhKdGFnMHZQSThQSG0xZkUKLS0tIFJ3WHhEbkNBMUlGcEhkeU5HNHdK
            NFBlakoyaUpsb2RLSW1LY0lKb3Nmc0kKHu8sAJlAoN3/+6gjrr/ykyswej8/zu2F
            9nm9OLYonFtV8ZhPEqQY+YcVQvvnXZRxmplVEUg9ZjBuHNSIcnOhRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:22:44Z"
    mac: ENC[AES256_GCM,data:oYDz/nuBWmApZp1KcoAUC+PbRWK6KYw7PjOFo31SZniU9HTirOmylNsTIgt1C+QYcBKQyu3GfjzIeISfKVoFo6ctRDYWNu9FhWvLJZRIbJYJ0PCU10qzCAm1+BGla4JYe3w1hBRd8aiyN9QSq0yHlgB76VbX8uVNOAFq2+KA7hE=,iv:kDS720KPWEQWHqWWjBjnwfKt+R21Z3P+R1byqKeEMr4=,tag:Lw9Gum2eDQafHvKzTO1Aog==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
